Fix: tests: AttributeError when test application unexpectedly exits
Observed issue
==============

When running the config-directory test on PPC 32-bit with Python 3.4,
the test fails with:

    AttributeError: 'NoneType' object has no attribute 'read'

This occurs in _WaitTraceTestApplication._wait_for_file_to_be_created()
when the test application unexpectedly exits.

Cause
=====

_WaitTraceTestApplication creates a subprocess with
stderr=subprocess.STDOUT (ln 453), which redirects stderr to stdout.

Per the Python documentation [1]:
>  "If the stderr argument was not PIPE, this attribute is None."

Since stderr is redirected to STDOUT rather than being set to PIPE,
self._process.stderr is None. However, the error handling code in
_wait_for_file_to_be_created() attempts to read from
self._process.stderr.read(), causing the AttributeError.

Solution
========

Read from self._process.stdout instead, since all output (both stdout
and stderr) is captured there due to the stderr=subprocess.STDOUT
redirection.

Known drawbacks
===============

None.

References
==========

[1] https://docs.python.org/3/library/subprocess.html#subprocess.Popen.stderr

Change-Id: Iba788588a8d69f44e0a434dfa01fe8a90ed0cb6d
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>