Make parse_arguments static in base_client.c
Fixes:

      CC base_client.o
    /home/smarchi/src/lttng-tools/tests/regression/tools/notification/base_client.c:60:5:
    error: no previous declaration for ‘parse_arguments’
    [-Werror=missing-declarations] int parse_arguments(char **argv) {
    ^~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I4e431009d6e174eaadd82d206f9bedde9efdd30b
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>