Build fix: mismatching exception specifier on g++ 4.8
Building on g++ 4.8 results in the following error:

field.hpp:259:2: error: function 'lttng::sessiond::trace::details::enumeration_mapping<MappingIntegerType>::enumeration_mapping(lttng::sessiond::trace::details::enumeration_mapping<MappingIntegerType>&&) [with MappingIntegerType = long int]' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'lttng::sessiond::trace::details::enumeration_mapping<long int>::enumeration_mapping(lttng::sessiond::trace::details::enumeration_mapping<long int>&&)'
   enumeration_mapping(enumeration_mapping<MappingIntegerType>&& other) noexcept = default;

The error occurs because the noexcept specifier in the defaulted move
constructor of the enumeration_mapping class conflicts with the implicit
exception specification generated by the compiler in older versions of
GCC (like 4.8). This is a known issue with older compilers that do not
fully support C++11 features.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I732b42db990d086141f939a6908bd16eaee511a4