Fix: build failure of gen-many-event-classes with `--code-coverage`
When building with `--code-coverage`, the build fails with the
following error:

    12:39:57 libtool: link: g++ -std=gnu++11 -Wno-redundant-decls -Wno-missing-field-initializers -g -O2 -o gen-many-event-classes/gen-many-event-classes gen-many-event-classes/gen_many_event_classes-gen-many-event-classes.o gen-many-event-classes/gen_many_event_classes-emit-events.o  -L/root/workspace/lttng-tools_master_root_linuxbuild_coverage/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/master/modules_aligned_access/default/node/deb13-amd64-rootnode/platform/deb13-amd64/deps//build/lib -L/build/lib ../../../src/common/.libs/libcommon-lgpl.a -lxml2 ../../../tests/utils/.libs/libtestutils.a ../../../src/vendor/argpar/.libs/libargpar.a gen-many-event-classes/.libs/libtp0.a gen-many-event-classes/.libs/libtp1.a gen-many-event-classes/.libs/libtp2.a gen-many-event-classes/.libs/libtp3.a gen-many-event-classes/.libs/libtp4.a gen-many-event-classes/.libs/libtp5.a gen-many-event-classes/.libs/libtp6.a gen-many-event-classes/.libs/libtp7.a gen-many-event-classes/.libs/libtp8.a gen-many-event-classes/.libs/libtp9.a -llttng-ust -llttng-ust-common -ldl -lrt -pthread
    12:39:57 /usr/bin/ld: ../../../src/common/.libs/libcommon-lgpl.a(exception.o): in function `_sub_I_00100_0':
    12:39:57 /root/workspace/lttng-tools_master_root_linuxbuild_coverage/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/master/modules_aligned_access/default/node/deb13-amd64-rootnode/platform/deb13-amd64/src/lttng-tools/src/common/exception.cpp:74:(.text.startup+0x8): undefined reference to `__gcov_init'
    12:39:57 /usr/bin/ld: ../../../src/common/.libs/libcommon-lgpl.a(exception.o): in function `_sub_D_00100_1':
    12:39:57 /root/workspace/lttng-tools_master_root_linuxbuild_coverage/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/master/modules_aligned_access/default/node/deb13-amd64-rootnode/platform/deb13-amd64/src/lttng-tools/src/common/exception.cpp:74:(.text.exit+0x1): undefined reference to `__gcov_exit'
    12:39:57 /usr/bin/ld: ../../../src/common/.libs/libcommon-lgpl.a(exception.o):(.data.rel+0x20): undefined reference to `__gcov_merge_add'
    12:39:57 collect2: error: ld returned 1 exit status
    12:39:57 make[5]: *** [Makefile:1387:
    gen-many-event-classes/gen-many-event-classes] Error 1

As gen-many-event-classes links against libcommon-lgpl, the Makefile
needs the static include to resolve the gcov libs.

The compilation and inlinking must also include the base CFLAGS, CXXFLAGS,
CPPFLAGS, and LDFLAGS as well.

Change-Id: Icac80c19d68801fb4ea113e4f0e5e55d9d9590dc
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>