Make functions in live_test.c static
Fixes:

      CC live_test.o
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:154:5:
    error: no previous declaration for ‘establish_connection’
    [-Werror=missing-declarations] int establish_connection(void)
    ^~~~~~~~~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:198:5:
    error: no previous declaration for ‘list_sessions’
    [-Werror=missing-declarations] int
    list_sessions(uint64_t *session_id) ^~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:245:5:
    error: no previous declaration for ‘create_viewer_session’
    [-Werror=missing-declarations] int create_viewer_session(void)
    ^~~~~~~~~~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:283:5:
    error: no previous declaration for ‘attach_session’
    [-Werror=missing-declarations] int attach_session(uint64_t id)
    ^~~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:372:5:
    error: no previous declaration for ‘get_metadata’
    [-Werror=missing-declarations] int get_metadata(void) ^~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:466:5:
    error: no previous declaration for ‘get_next_index’
    [-Werror=missing-declarations] int get_next_index(void)
    ^~~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/regression/tools/live/live_test.c:631:5:
    error: no previous declaration for ‘detach_viewer_session’
    [-Werror=missing-declarations] int detach_viewer_session(uint64_t
    id) ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I7dc82076439e1bccd7bc253d084291f6281f6887
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>