tests: Split test_ust_constructor into several tests
Observed issue
==============

TAP parsers fail when parsing a single executable that contains
several plans. Eg.,

```
ok 44 - Found no unexpected events
PASS: ust/ust-constructor/test_ust_constructor.py 44 - Found no unexpected events

1..44
ERROR: ust/ust-constructor/test_ust_constructor.py - multiple test plans
ok 1 - Create a session
ERROR: ust/ust-constructor/test_ust_constructor.py 1 - Create a session # UNPLANNED
```

and

```
14:03:23 org.tap4j.parser.ParserException: Error parsing TAP Stream: Duplicated TAP Plan found.
14:03:23 	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:257)
14:03:23 	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:231)
14:03:23 	at org.tap4j.plugin.TapParser.parse(TapParser.java:172)
14:03:23 	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:475)
14:03:23 	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:352)
14:03:23 	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:312)
14:03:23 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
14:03:23 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
14:03:23 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:03:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
14:03:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
14:03:23 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
14:03:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
14:03:23 	at hudson.model.Run.execute(Run.java:1918)
14:03:23 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
14:03:23 	at hudson.model.ResourceController.execute(ResourceController.java:101)
14:03:23 	at hudson.model.Executor.run(Executor.java:442)
14:03:23 Caused by: org.tap4j.parser.ParserException: Duplicated TAP Plan found.
14:03:23 	at org.tap4j.parser.Tap13Parser.parseLine(Tap13Parser.java:354)
14:03:23 	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:252)
14:03:23 	... 16 more
```

Cause
=====

09a872ef0b4e1432329aa42fecc61f50e9baa367 introduced multiple plans in
to test_ust_constructor

Solution
========

Split the script into several smaller test scripts sharing a common
import for data and the bulk of execution.

Known drawbacks
===============

None.

Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I81649d714afe0e325996b730d5c72cfd5b28d1f8