lttng: handle popt parsing errors
Instead of returnning a generic "Unrecognized argument" error for all
types of popt parsing error, use poptBadOption() and poptStrerror() to
print a specific error message which references the problematic option.

Before:

 $ lttng view -e
 Error: Unrecognized argument used with 'view' command

 $ lttng view -Z
 Error: Unrecognized argument used with 'view' command

After:

 $ lttng view -e
 Error: Option '-e': missing argument

 $ lttng view -Z
 Error: Option '-Z': unknown option

Change-Id: Ic2ae703d3562b197f3f6e70f3760b50c17dac82e
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>