Fix: sessiond: build fails with libxml2 2.14+
Building against libxml2 2.14.2 results in the following build error:

  config/session-config.cpp: In function 'xmlChar* encode_string(const char*)':
  config/session-config.cpp:297:24: warning: '_xmlCharEncodingHandler::input' is deprecated [-Wdeprecated-declarations]
    297 |         ret = handler->input(out_str, &out_len, (const xmlChar *) in_str, &in_len);
        |                        ^~~~~
  In file included from /usr/include/libxml2/libxml/xmlIO.h:16,
                   from /usr/include/libxml2/libxml/xmlwriter.h:18,
                   from config/config-internal.hpp:8,
                   from config/session-config.cpp:10:
  /usr/include/libxml2/libxml/encoding.h:173:7: note: declared here
    173 |     } input XML_DEPRECATED_MEMBER;
        |       ^~~~~
  config/session-config.cpp:297:24: warning: '_xmlCharEncodingHandler::input' is deprecated [-Wdeprecated-declarations]
    297 |         ret = handler->input(out_str, &out_len, (const xmlChar *) in_str, &in_len);
        |                        ^~~~~
  /usr/include/libxml2/libxml/encoding.h:173:7: note: declared here
    173 |     } input XML_DEPRECATED_MEMBER;
        |       ^~~~~
  config/session-config.cpp:297:24: warning: '_xmlCharEncodingHandler::input' is deprecated [-Wdeprecated-declarations]
    297 |         ret = handler->input(out_str, &out_len, (const xmlChar *) in_str, &in_len);
        |                        ^~~~~
  /usr/include/libxml2/libxml/encoding.h:173:7: note: declared here
    173 |     } input XML_DEPRECATED_MEMBER;
        |       ^~~~~
  config/session-config.cpp:297:29: error: no match for call to '(_xmlCharEncodingHandler::<unnamed union>) (xmlChar*&, int*, const xmlChar*, int*)'
    297 |         ret = handler->input(out_str, &out_len, (const xmlChar *) in_str, &in_len);
        |               ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

libxml marks the input member of xmlCharEncodingHandlerPtr as deprecated
and moves the function pointer of the structure to a union.

The xmlCharEncInFunc API is now used for string encoding. This change
requires the use of xmlBuffer, leading to a modification of the
encode_string() function to return an `encoded_string` instance. The
`encoded_string` class wraps the xmlBuffer and provides a conversion
operator to xmlChar for seamless integration.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I88606d5542683025339b86efa390ec698e70cf95