Clean-up: lttng-ctl: remove unused variable
Fix:

      CXX      lttng-ctl.lo
    /home/simark/src/lttng-tools/src/lib/lttng-ctl/lttng-ctl.cpp: In function 'int lttng_enable_channel(lttng_handle*, lttng_channel*)':
    /home/simark/src/lttng-tools/src/lib/lttng-ctl/lttng-ctl.cpp:1549:31: error: unused variable 'ret_code' [-Werror=unused-variable]
     1549 |         enum lttng_error_code ret_code;
          |                               ^~~~~~~~

Change-Id: Ie3b12eb9fba99578a677b1679147ea29daddb653
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>