Fix: lttng-sessiond: control reaches end of non-void function warning
Fixes the following error when building with GCC 7.4.0 with the
following CFLAGS: "-g -fsanitize=address":

  tracker.c: In function ‘lttng_tracker_id_lookup_string’:
  tracker.c:405:1: error: control reaches end of non-void function [-Werror=return-type]
   }
   ^

At first glance, this seems like a false positive. I don't see how we
can reach the end of the function without passing by a return statement.

Even considering that, removing the `break` statement makes sense
because it's superfluous.

Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>
Change-Id: I0b596d328bc38183f21bd3a6f8419a63207953f3
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>