Fix: tests: Set mip version for python defined bt graphs explicitly
Observed issue
==============

When using babeltrace2 master,
`tests/regression/tools/lttng-ctl/test_robust_protocol.py` fails with
the following error:

    not ok 1 - test_simple - Exception: cannot add component to graph
    ERROR:    [libbabeltrace2] (lib/graph/graph.c:1203)
      Component initialization method failed: status=ERROR, comp-addr=0x3abf9b70,
      comp-name="source", comp-log-level=NONE, comp-class-type=SOURCE,
      comp-class-name="fs", comp-class-partial-descr="Read CTF traces from the file
      sy", comp-class-is-frozen=0, comp-class-so-handle-addr=0x3a9e0b40,
      comp-class-so-handle-path="/home/kstewart/src/efficios/lttng/master/usr/lib/babeltrace2/plugins/babeltrace-plugin-ctf.so",
      comp-input-port-count=0, comp-output-port-count=0
    CAUSED BY [source: 'source.ctf.fs'] (plugins/ctf/fs-src/fs.cpp:511)
      CTF 2 traces are not supported with MIP version 0; consider creating the graph
      with MIP version 1:
      path="/tmp/lttng_test_env_homeeuks0hak/tracewyzsub0t/20260217T100616-0500-1/ust/uid/1000/64-bit",
      name="(null)"

Cause
=====

The python bindings for BT2 set the mip version to 0 by default. MIP
version 1 is required for CTF2 traces.

Solution
========

Use mip 1 explicitly.

Known drawbacks
===============

None.

Change-Id: I5971edc9bde2dbdda2e44bee0082fc70d725b54e
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>