Build fix: relayd: be64toh doesn't return uint64_t on Windows
The build on Windows fails since da5f0388, which introduced
stricter type checking when assigning values to LTTNG_OPTIONAL
fields.

  In file included from ../../../src/common/credentials.hpp:12,
                   from ../../../src/common/compat/directory-handle.hpp:11,
                   from ../../../src/common/trace-chunk.hpp:11,
                   from ../../../src/common/index/index.hpp:16,
                   from index.hpp:14,
                   from stream.cpp:12:
  stream.cpp: In function â€˜int stream_update_index(relay_stream*, uint64_t, bool, bool*, uint64_t)â€™:
  ../../../src/common/optional.hpp:100:81: error: static assertion failed: Type mismatch between optional field and value
     99 |                         std::is_same<typename std::decay<decltype((field_ptr)->value)>::type, \
        |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    100 |                                      typename std::decay<decltype(val)>::type>::value,        \
        |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  stream.cpp:1186:17: note: in expansion of macro â€˜LTTNG_OPTIONAL_SETâ€™
   1186 |                 LTTNG_OPTIONAL_SET(&stream->received_packet_seq_num,

Performing the endian-ness conversion in a separate statement
makes the code easier to read and also fixes this issue by
performing an implicit cast to uin64_t on that platform.

Change-Id: I37c61572869e6db961957a858322ba3ef00a060a
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>