fix: multiple test failure when missing gdb
There is a typo in the python code path handling a missing gdb in
multiple tests that results in failure instead of the intended skipping.
Simply replace 'tap.missing_platform_requirements' with
'tap.missing_platform_requirement'.

An example test failure when gdb is missing:

  ERROR: tools/notification/test_notification_ust_multi_app.py
  ============================================================

  Traceback (most recent call last):
    File "/<<PKGBUILDDIR>>/tests/regression/./tools/notification/test_notification_ust_multi_app.py", line 45, in <module>
      tap.missing_platform_requirements("Need gdb")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'TapGenerator' object has no attribute 'missing_platform_requirements'. Did you mean: 'missing_platform_requirement'?
  1..2
  Bail out! Missing 2 test cases
  ERROR: tools/notification/test_notification_ust_multi_app.py - Bail out! Missing 2 test cases
  Exception ignored while calling deallocator <function TapGenerator.__del__ at 0x71ff8b36cb40>:
  Traceback (most recent call last):
    File "/<<PKGBUILDDIR>>/tests/utils/lttngtest/tap_generator.py", line 118, in __del__
    File "/<<PKGBUILDDIR>>/tests/utils/lttngtest/tap_generator.py", line 168, in bail_out
  lttngtest.tap_generator.BailOut: Missing 2 test cases

Change-Id: I92739c5c739f84523f7893201be4390539dd55eb
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>