tests: Use `os.walk()` instead of `Path.walk()` in `test_shellcheck`
`Path.walk` was introduced in Python 3.12.

With older versions of Python the follow error occurs:

    Traceback (most recent call last):
      File "/home/jenkins/workspace/lttng-tools_master_elbuild/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/stable-0.15/platform/el9-amd64/src/lttng-tools/tests/meta/./test_shellcheck", line 202, in <module>
        files = identify_shell_files(project_root, directories, exclusions)
      File "/home/jenkins/workspace/lttng-tools_master_elbuild/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/stable-0.15/platform/el9-amd64/src/lttng-tools/tests/meta/./test_shellcheck", line 43, in identify_shell_files
        for _directory, dirnames, filenames in (base_path / directory).walk():
    AttributeError: 'PosixPath' object has no attribute 'walk'
    ERROR: test_shellcheck - missing test plan
    ERROR: test_shellcheck - exited with status 1

Change-Id: Icc62a9e3ca37010668d52fbfb30c26b0b2f8d28c
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>