Fix: container-wrapper: add missing comparison operators for _GLIBCXX_DEBUG
Observed issue
==============

When building with -D_GLIBCXX_DEBUG, the build fails with:

  In file included from bt2_plugins/event_name/event_name.cpp:8:
  In file included from bt2_plugins/event_name/../utils.hpp:11:
  In file included from ../../src/common/make-unique-wrapper.hpp:12:
  In file included from ../../src/common/meta-helpers.hpp:11:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/memory:69:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_uninitialized.h:63:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_algobase.h:67:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_iterator.h:3020:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/debug/stl_iterator.h:32:
  /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/debug/helper_functions.h:185:13: error: invalid operands to binary expression ('lttng::utils::random_access_container_wrapper<const bt_value *, const char *, event_name_set_operations>::_iterator<const lttng::utils::random_access_container_wrapper<const bt_value *, const char *, event_name_set_operations>, const char *const>' and 'lttng::utils::random_access_container_wrapper<const bt_value *, const char *, event_name_set_operations>::_iterator<const lttng::utils::random_access_container_wrapper<const bt_value *, const char *, event_name_set_operations>, const char *const>')
    185 |         && __first <= __last;

Cause
=====

The random_access_container_wrapper's _iterator class only implements
operator== and operator!=. When compiling with -D_GLIBCXX_DEBUG, the
libstdc++ debug mode performs additional validation that requires the
full set of comparison operators (operator<, operator<=, operator>,
operator>=) for random access iterators.

The debug helper functions in <debug/helper_functions.h> use these
operators to validate iterator ranges.

Solution
========

Add the missing comparison operators (operator<, operator<=, operator>,
operator>=) to the _iterator class. These operators compare the
underlying index values, which is the expected semantic for this
index-based random access iterator.

Change-Id: I4ec5bc5ebca53fe8888186b2c4cbd872130938ae
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>