Make remove_file_from_hierarchy function static in test_directory_handle.c
Fixes:

      CC test_directory_handle.o
    /home/smarchi/src/lttng-tools/tests/unit/test_directory_handle.c:139:5:
    error: no previous declaration for ‘remove_file_from_hierarchy’
    [-Werror=missing-declarations] int
    remove_file_from_hierarchy(struct
    lttng_directory_handle *test_dir_handle,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I060a89d88f2de8e12368496968708d273cb318f2
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>