Fix: sessiond: domain subdirectory not deleted on empty clear
Scenario
=====

$ lttng create
$ lttng enable-event -u -a
$ lttng start

// no events are produced.

$ lttng clear

Sessiond fails on clear with this message:

Error: Error removing subdirectory '.tmp_new_chunk' file when deleting
chunk

Cause
=====

The "ust" domain directory is still present preventing the removal of
the ".tmp_new_chunk" directory.

Solution
=====

Use lttng_trace_chunk_create_subdirectory, ensuring that the domain
folder is moved/deleted as necessary.

Fixes #1244

Signed-off-by: Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
Change-Id: I81d23ffc9f330f50f718957d460ee7a2718c95a1
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>