common: make some functions static in mi-lttng.c
These two functions are only used in the file, so make them static.

Fixes:

      CC       mi-lttng.lo
    /home/smarchi/src/lttng-tools/src/common/mi-lttng.c:367:13: error: no previous declaration for ‘mi_lttng_eventtype_string’ [-Werror=missing-declarations]
     const char *mi_lttng_eventtype_string(enum lttng_event_type value)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
    /home/smarchi/src/lttng-tools/src/common/mi-lttng.c:1317:5: error: no previous declaration for ‘mi_lttng_event_userspace_probe’ [-Werror=missing-declarations]
     int mi_lttng_event_userspace_probe(struct mi_writer *writer,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are a bunch of other stuff in mi-lttng.c that could be made
static, but those were the only two problematic with
-Wmissing-declarations, because there have no declaration in the .h.

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I9f3a6b0f71e86fac7af5d40e553a6944eb768fbe
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>