lttng: Fix help output when unknown action is given in add-trigger
Observed issue
==============

When running `lttng add-trigger` with an unknown action, not all
action names were listed in the help output.

    $ ./src/bin/lttng/.libs/lttng add-trigger --action asdf
    Error: While parsing argument #8 (`--action`): Unknown action name 'asdf'
    Error: Valid action names are:
    Error:   notify
    Error:   start-session

Cause
=====

The wrong description array was being used as the upper-bound for
iteration of action descriptions.

Solution
========

Use the correct array length.

Drawbacks
=========

None.

Change-Id: I4c7476185c7d28f2cf6aac5ecd29303d049fd53d
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>