tests: Handle race when checking tracing done sync file
Observed on yocto40-ppc64 in
`tests/regression/tools/config-directory/test_config.py`:

    # Launching test application: '/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/stable-0.15/platform/yocto40-ppc64/src/lttng-tools/tests/utils/testapp/gen-ust-events --iter 100 --sync-application-in-main-touch /tmp/tmp.9Z7SNWyjZu/app_v2hlr1v1_ready --sync-before-first-event /tmp/tmp.9Z7SNWyjZu/app_afppcozq_start_tracing --sync-before-last-event-touch /tmp/tmp.9Z7SNWyjZu/app_lsj2ieed_before_last_event --sync-before-exit-touch /tmp/tmp.9Z7SNWyjZu/app_rdib_2bb_done_tracing'
    # test-app-gen-ust-events: gen-ust-events: starting: 100 iter 0 usec wait
    # test-app-gen-ust-events: gen-ust-events: sync-application-in-main-touch: create /tmp/tmp.9Z7SNWyjZu/app_v2hlr1v1_ready
    # test-app-gen-ust-events: gen-ust-events: sync-before-first-event: wait /tmp/tmp.9Z7SNWyjZu/app_afppcozq_start_tracing
    # [1837475] Tracing started
    # test-app-gen-ust-events: gen-ust-events: sync-before-last-event-touch: create /tmp/tmp.9Z7SNWyjZu/app_lsj2ieed_before_last_event
    # test-app-gen-ust-events: gen-ust-events: sync-before-exit-touch: create /tmp/tmp.9Z7SNWyjZu/app_rdib_2bb_done_tracing
    # Termination signal sent to session daemon (pid = 1837380)
    # Session daemon killed
    # Termination signal sent to relayd (pid = 1837370)
    # Relayd killed
    Traceback (most recent call last):
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/stable-0.15/platform/yocto40-ppc64/src/lttng-tools/tests/regression/tools/config-directory/test_config.py", line 324, in <module>
        test_config_and_socket_paths(test_env, tap, test_identifier, **temp_conf)
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/stable-0.15/platform/yocto40-ppc64/src/lttng-tools/tests/regression/tools/config-directory/test_config.py", line 231, in test_config_and_socket_paths
        test_app.wait_for_tracing_done()
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/stable-0.15/platform/yocto40-ppc64/src/lttng-tools/tests/utils/lttngtest/environment.py", line 551, in wait_for_tracing_done
        self._wait_for_file_to_be_created(self._app_tracing_done_file_path)
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/stable-0.15/platform/yocto40-ppc64/src/lttng-tools/tests/utils/lttngtest/environment.py", line 481, in _wait_for_file_to_be_created
        raise RuntimeError(
    RuntimeError: Test application has unexepectedly returned while waiting for synchronization file to be created: sync_file=`/tmp/tmp.9Z7SNWyjZu/app_rdib_2bb_done_tracing`, return_code=`0`, output=``

Change-Id: I7644a087bb49abe36b20d5ee6caf13978e2685f0
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>