Build fix: missing header on macOS
The build fails on macOS (on both ARM64 and AMD64 platforms):
  exception.cpp:32:41: error: use of undeclared identifier 'error_get_str'
          runtime_error(msg + ": " + std::string(error_get_str(error_code)),
                                                 ^

error_get_str is defined in lttng/lttng-error.h

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I69fa0c0bc442d0cb28779f6b4c55d0b6a7196791