consumerd: remove unused function consumer_del_data_stream
Fix:

      CC       consumer.lo
    /home/smarchi/src/lttng-tools/src/common/consumer/consumer.c:712:6: error: no previous declaration for ‘consumer_del_data_stream’ [-Werror=missing-declarations]
     void consumer_del_data_stream(struct lttng_consumer_stream *stream)
          ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I92a47e069055713eaa4fdbc7f034a8f8e439f283
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>