Tests: `text` option of subprocess.Popen was introduced in Python 3.7
Some of our supported platforms ship with an older Python interpreter
resulting in the following failures:

trace_format_helpers.py", line 363, in convert_trace_to_text_pretty
    text=True,
TypeError: __init__() got an unexpected keyword argument 'text'

Replacing the `text=True` parameter in subprocess calls with
`universal_newlines=True` ensures compatibility with older Python
versions (pre-3.7) while maintaining the same functionality for handling
text streams.

The `text` parameter is documented as having the same behaviour as
`universal_newlines`. It was introduced to maintain a base level of
breakage and churn.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I35173ab65c65fd16220e9ed37841e99bcc96d6b5