Clean-up: remove instances of loop initial declarations
Loop initial declarations are not permitted by the project's
coding standard and cause the build to fail on Solaris platforms.

tracker.c: In function 'lttng_tracker_ids_serialize':
tracker.c:314:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (unsigned int i = 0; i < count; i++) {
  ^
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>

Change-Id: I627974ef82ca26586c96d354f217f9943db9d67c