tests: Define environment attributes before launching relayd/sessiond
This helps to avoid exceptions during the the object destructor,
e.g. during an early crash:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/src/bin/lttng-sessiond/lttng-sessiond'
Exception ignored in: <function _Environment.__del__ at 0x7f48394272e0>
Traceback (most recent call last):
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/tests/utils/lttngtest/environment.py", line 1462, in __del__
    self._cleanup()
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/tests/utils/lttngtest/environment.py", line 1401, in _cleanup
    if self._sessiond and self._sessiond.poll() is None:
AttributeError: '_Environment' object has no attribute '_sessiond'
1..2
Bail out! Missing 2 test cases
ERROR: tools/client/test_reclaim_memory.py - Bail out! Missing 2 test cases
Exception ignored in: <function TapGenerator.__del__ at 0x7f4839ecaa20>
Traceback (most recent call last):
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 101, in __del__
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 151, in bail_out
lttngtest.tap_generator.BailOut: Missing 2 test cases
```

Change-Id: Ic23a53c538f574c0d9d4aa27def230977cf89680
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>