Make create_file function static in gen-ust-tracef.c
Fixes:

      CC gen-ust-tracef.o
    /home/smarchi/src/lttng-tools/tests/utils/testapp/gen-ust-tracef/gen-ust-tracef.c:36:6:
    error: no previous declaration for ‘create_file’
    [-Werror=missing-declarations] void create_file(const char *path)
    ^~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I12359b30054da609be2aca998de960719120083e
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>