Tests: fix: kernel/test_callstack: number of tests on i386
The number of planned tests is incorrect when not running the userspace
callstack tests which is limited to x86_64.

Fixes the following error:

  ERROR: kernel/test_callstack 12 - Wait after kill session daemon # UNPLANNED
  # Looks like you planned 11 tests but ran 1 extra.
  ERROR: kernel/test_callstack - too many tests run (expected 11, got 12)
  ERROR: kernel/test_callstack - exited with status 1

Change-Id: Icf662968ac977b08594eca99e18476e43cc4ea79
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>