Fix: Ensure disconnected mux inport port is used when making connections
In `test_robust_protocol.py` the following error was observed
intermittently on yocto23-powerpc:

    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:64 Babeltrace 2 library precondition not satisfied.
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:65 ------------------------------------------------------------------------
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:66 Condition ID: `pre:graph-connect-ports:downstream-port-is-not-connected`.
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:68 Function: bt_graph_connect_ports().
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:69 ------------------------------------------------------------------------
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:70 Error is:
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:72 Downstream port is already connected: addr=0x10209020, type=INPUT, name="in0"
    12-08 22:00:06.525 2444 2444 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:75 Aborting...

With further debug output added to should the ports being connected:

    # lttng rotate 'session_c2t0kkj7'
    <bt2.component._ComponentPorts object at 0xb6d1ae90>
    : `lttng.org,2009`, name: ``, uid:
    `57d005f5-6a97-497b-8e77-ce7f8072a993`} | 0 | 0
    .port._InputPortConst object @ 0x101ddfa0>
    : `lttng.org,2009`, name: ``, uid: `57d005f5-6a97-497b-8e77-ce7f8072a993`} | 0 | 1
    <bt2.port._InputPortConst object @ 0x101ddfa0>

It seems that the `[-1]` port is not always the newest disconnected
port. The underlying cause for that has not been investigated. As far
as I know this has only failed with Python 3.5, so it could
potentially be related to an implementation detail in that version.

This works-around the issue by filtering all the mux input ports to
remove those are already connected.

Change-Id: I02cbb557624ea4fee6b8f47d9aa443272dd3f492
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>