tests: add declarations for functions in gen-syscall-events-callstack.c
Fixes:

      CC       gen-syscall-events-callstack.o
    /home/smarchi/src/lttng-tools/tests/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack.c:46:1: error: no previous declaration for ‘my_gettid’ [-Werror=missing-declarations]
     my_gettid(void)
     ^~~~~~~~~
    /home/smarchi/src/lttng-tools/tests/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack.c:72:1: error: no previous declaration for ‘fct_c’ [-Werror=missing-declarations]
     fct_c(void)
     ^~~~~
    /home/smarchi/src/lttng-tools/tests/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack.c:78:1: error: no previous declaration for ‘fct_b’ [-Werror=missing-declarations]
     fct_b(void)
     ^~~~~
    /home/smarchi/src/lttng-tools/tests/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack.c:85:1: error: no previous declaration for ‘fct_a’ [-Werror=missing-declarations]
     fct_a(void)
     ^~~~~

From what I understand, it is important that these symbols stay exported
for test regression/kernel/test_callstack.

Change-Id: I656a4e77bb2653510ba971e94ccc0d8bb65be698
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>