Fix: tests: include callsites.h from callsites.c
In commit:

    commit f12eb9c1ceb619db54be0842323a32cda12651cd
    Author: Simon Marchi <simon.marchi@efficios.com>
    Date:   Mon Nov 25 16:41:29 2019 -0500

        Fix all -Wmissing-declarations warning instances

I've fixed the -Wmissing-declarations warning in callsites.c by adding a local
declaration.  That was wrong, since there is actually a callsites.h header file
that needs to be included, which contains the declaration.  This is nicely
pointed out when building with clang and -Wstrict-prototypes:

      CC       exec_with_callsites-multi-lib-test.o
    In file included from /home/simark/src/lttng-tools/tests/regression/ust/multi-lib/multi-lib-test.c:15:
    /home/simark/src/lttng-tools/tests/regression/ust/multi-lib/callsites.h:10:21: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
    void call_tracepoint();
                        ^
                         void

Remove the local declaration and include callsites.h in callsites.c.

Change-Id: Ib656d96c2ed3b389697a2022e343e98ac0b66447
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>