tests: Fix: online_cpus() fails with disjoint sets
Observed issue
==============

A test failed in the CI as follows:

```

ERROR: ust/high-throughput/test_high_throughput_snapshot.py
===========================================================

Traceback (most recent call last):
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/std/conf/std/liburcu_version/master/platform/deb12-amd64/src/lttng-tools/tests/regression/./ust/high-throughput/test_high_throughput_snapshot.py", line 195, in <module>
    test_high_throughput_snapshot(tap, test_env)
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/std/conf/std/liburcu_version/master/platform/deb12-amd64/src/lttng-tools/tests/regression/./ust/high-throughput/test_high_throughput_snapshot.py", line 63, in test_high_throughput_snapshot
    online_cpus = list(lttngtest.online_cpus())
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/std/conf/std/liburcu_version/master/platform/deb12-amd64/src/lttng-tools/tests/utils/lttngtest/environment.py", line 1249, in online_cpus
    start, end = cpu_range.split("-")
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
1..3
Bail out! Missing 3 test cases
ERROR: ust/high-throughput/test_high_throughput_snapshot.py - Bail out! Missing 3 test cases
Exception ignored in: <function TapGenerator.__del__ at 0x7f50f6a44400>
Traceback (most recent call last):
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/std/conf/std/liburcu_version/master/platform/deb12-amd64/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 95, in __del__
  File "/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/std/conf/std/liburcu_version/master/platform/deb12-amd64/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 145, in bail_out
lttngtest.tap_generator.BailOut: Missing 3 test cases
```

Cause
=====

`online_cpus()` assumed values would also be joined by a dash.

Solution
========

Check if `cpu_range` contains a dash before splitting on that
character.

Known drawbacks
===============

None.

Change-Id: I1684db2d658fb9e9127dcf74a182713960949746
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>