relayd: Remove unused consumer includes from health-relayd
As the consumer-timer now only supports linux, when building with
relayd-only on a non-linux OS, the build would fail as follows:

    11:43:02 In file included from health-relayd.cpp:16:
    11:43:02 In file included from ../../../src/common/consumer/consumer-timer.hpp:13:
    11:43:02 In file included from ../../../src/common/consumer/consumer.hpp:22:
    11:43:02 In file included from ../../../src/common/task-executor.hpp:11:
    11:43:02 ../../../src/common/poller.hpp:22:10: fatal error: 'sys/epoll.h' file not found
    11:43:02    22 | #include <sys/epoll.h>
    11:43:02       |          ^~~~~~~~~~~~~
    11:43:02 1 error generated.

There doesn't seem to be a reason to include `consumer.hpp` or
`consumer-timer.hpp` in this file.

Change-Id: I6cc0267e6d90b814e45d628d747d4ef05220ef39
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>