Build fix: OOT build fails for sema test app
Since 9fa0166a7, the out-of-tree build of the sema test application
fails with:

tools/tests/utils/testapp/sema.c:14:10: fatal error: foobar_provider.h: No such file or directory
   14 | #include "foobar_provider.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [Makefile:1065: sema.o] Error 1
make[5]: *** Waiting for unfinished jobs....
/home/jenkins/workspace/dev_review_lttng-tools_master_linuxbuild/babeltrace_version/master/build/oot/conf/std/liburcu_version/master/platform/deb13-amd64/src/lttng-tools/tests/utils/testapp/userspace-probe-sdt-binary.c:19:10: fatal error: foobar_provider.h: No such file or directory
   19 | #include "foobar_provider.h"
      |          ^~~~~~~~~~~~~~~~~~~

The build directory must be part of the app's (and its libraries')
include path since foobar_provider.h is generated by dtrace during
the build.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>