sessiond: Relax CTF 1.8 TSDL identifier validation
Observed issue
==============

When tracing an application that has an event field with an empty
identifier, LTTng 2.14.0+ would fail to produce unreadable traces and
show errors during metadata regeneration.

E.g. Unreadable trace:

```
$ lttng view
Trace directory: auto-20260109-102441

01-09 10:24:55.933 1015776 1015776 E PLUGIN/CTF/ITEM-SEQ-ITER _handleSetEventRecordInfoItemState@plugins/ctf/common/src/item-seq/item-seq-iter.cpp:590 At 720 bits: no event record class exists with ID 27 within the data stream class with ID 0.
01-09 10:24:55.933 1015776 1015776 E PLUGIN/CTF/MSG-ITER next@plugins/ctf/common/src/msg-iter.cpp:83 Failed to create the next message: addr=0x5629baf7a
```

E.g. Error during metadata regeneration

```
Error: Failed to regenerate user space session metadata: Invalid 0-length identifier used in trace description
Error: Failed to regenerate the UST metadata
Warning: Command returned an invalid status code, returning unknown error: command type = REGENERATE_METADATA (32), ret = -1
```

Cause
=====

Given a LTTng-UST tracepoint event definition as follows:

```
LTTNG_UST_TRACEPOINT_EVENT(ust_tests_demo, starting,
	LTTNG_UST_TP_ARGS(int, value),
	LTTNG_UST_TP_FIELDS(
		lttng_ust_field_integer(int, , value)
	)
)
```

The event will be created with an empty identifier for the integer
field.

In CTF 1.8, a field may not have an empty identifier. The allowed
identifiers are `[a-zA-Z]` and `[0-9]`, optionally prefixed with
`_`[1][2].

Using LTTng-tools 2.13.8, the metadata for the tracepoint event
resembles:

```
event {
        name = "ust_tests_demo:starting";
        id = 27;
        stream_id = 0;
        loglevel = 2;
        model.emf.uri = "http://example.com/path_to_model?q=ust_tests_demo:starting";
        fields := struct {
                integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _;
        };
};
```

In CTF 2.0, the identifiers are any valid JSON string, which may be
empty[3][4], and produces metadata similar to the following:

```
{
  "attributes": {
    "lttng.org,2009": {
      "emf-uri": "http://example.com/path_to_model?q=ust_tests_demo:starting",
      "log-level": "critical"
    }
  },
  "data-stream-class-id": 0,
  "id": 27,
  "name": "ust_tests_demo:starting",
  "payload-field-class": {
    "member-classes": [
      {
        "field-class": {
          "alignment": 8,
          "byte-order": "little-endian",
          "length": 32,
          "preferred-display-base": 10,
          "type": "fixed-length-signed-integer"
        },
        "name": ""
      }
    ],
    "type": "structure"
  },
  "type": "event-record-class"
}
```

In LTTng <= 2.13, the metadata generated seems to always prefix
identifiers with dans "_"[5], and there was no check for the length of
identifiers.

Solution
========

Remove the check for zero-length identifiers when escaping TSDL
identifiers.

Known drawbacks
===============

None.

References
==========

[1]: https://diamon.org/ctf/v1.8.3/#specC.1.3
[2]: https://diamon.org/ctf/v1.8.3/#spec4.2.1
[3]: https://diamon.org/ctf/#fca-frag
[4]: https://diamon.org/ctf/#struct-member-cls
[5]: https://github.com/lttng/lttng-tools/blob/810703b69692d0d9ffc8f0663f94da2b3d61af8c/src/bin/lttng-sessiond/ust-metadata.c#L456

Change-Id: I21e5a9e1fac67436d32d540c0805b7924a64bdcf
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>