Build fix: const type decltype marked as const
gcc 4.8 complains that:

ust-field-convert.cpp:775:21:   required from here
ust-field-convert.cpp:657:37: error: 'const' qualifiers cannot be applied to 'const std::pair<const std::basic_string<char>, lttng::sessiond::trace::details::enumeration_mapping<long unsigned int> >&'
          ->begin())& nameMappingPair) {
                                     ^
ust-field-convert.cpp:657:22: error: 'const' qualifiers cannot be applied to 'const std::pair<const std::basic_string<char>, lttng::sessiond::trace::details::enumeration_mapping<long unsigned int> >&'
          ->begin())& nameMappingPair) {
                      ^

The extra const qualifier is removed to allow the build to go through.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I515c9b192b9c32722c14394ce58e1463b8b5b47f