Fix: kernel-consumer: prepend kernel TSDL metadata stream with header
Observed issue
==============

When running kernel tracing tests (such as
`tests/regression/tools/clear/test_kernel`) with Babeltrace 2.0, the
tests fail to parse traces.

    # ./tests/regression/tools/clear/test_kernel
    1..839
    # Clear - Kernel tracing
    ok 1 - 0 LTTng modules loaded, expected count = 0
      ---
        duration_ms: 10.313797
      ...
    # Relayd log file: /dev/null
    # Run: src/bin/lttng-relayd/lttng-relayd -o /tmp/tmp.test_clear_kernel_trace_path.ToEbiW --pid-file /tmp/lttng_relayd_pid.FBaMhO --sig-parent
    ok 2 - Start lttng-relayd (opts: -o /tmp/tmp.test_clear_kernel_trace_path.ToEbiW --pid-file /tmp/lttng_relayd_pid.FBaMhO --sig-parent)
      ---
        duration_ms: 122.360486
      ...
    # export LTTNG_SESSION_CONFIG_XSD_PATH=/home/kstewart/src/efficios/lttng/master/src/lttng-tools/src/common/
    # env /home/kstewart/src/efficios/lttng/master/src/lttng-tools/src/bin/lttng-sessiond/lttng-sessiond --consumerd64-path=/home/kstewart/src/efficios/lttng/master/src/lttng-tools/src/bin/lttng-consumerd/lttng-consumerd 1
    ok 3 - Start session daemon
      ---
        duration_ms: 2051.387621
      ...
    # Test kernel streaming clear
    # Parameters: tracing_active=1, clear_twice=0, rotate_before=0, rotate_after=0
    # Run: src/bin/lttng/lttng create ZgIKdBhInjlz7sEs -U net://localhost
    ok 4 - Create session 'ZgIKdBhInjlz7sEs' with uri 'net://localhost' and options:
      ---
        duration_ms: 85.886520
      ...
    # Run: src/bin/lttng/lttng enable-event lttng_test_filter_event -s ZgIKdBhInjlz7sEs -k
    ok 5 - Enable kernel event 'lttng_test_filter_event for session 'ZgIKdBhInjlz7sEs' on channel ''
      ---
        duration_ms: 231.344409
      ...
    # Run: src/bin/lttng/lttng start ZgIKdBhInjlz7sEs
    ok 6 - Start tracing for session 'ZgIKdBhInjlz7sEs'
      ---
        duration_ms: 81.146140
      ...
    # Run: src/bin/lttng/lttng clear ZgIKdBhInjlz7sEs
    ok 7 - Clear session 'ZgIKdBhInjlz7sEs'
      ---
        duration_ms: 580.954943
      ...
    # Run: src/bin/lttng/lttng stop ZgIKdBhInjlz7sEs
    ok 8 - Stop lttng tracing for session 'ZgIKdBhInjlz7sEs'
      ---
        duration_ms: 283.264833
      ...
    # babeltrace2 /tmp/tmp.test_clear_kernel_trace_path.ToEbiW/laptop-kstewart/ZgIKdBhInjlz7sEs-20250930-154334  # Error log: '/dev/null'
    not ok 9 - Failed to parse trace
      ---
        duration_ms: 30.589789
      ...
    #   Failed test 'Failed to parse trace'
    #   in
    #   ./tests/regression/tools/clear//../../../utils/tap/tap.sh:fail()
    #   at line 170.

Example error log from babeltrace 2.0:

```
09-30 15:47:43.080 534979 534979 W PLUGIN/CTF/META/DECODER ctf_metadata_decoder_append_content@decoder.c:250 [N/A] Missing "/* CTF major.minor" signature in plain text metadata file stream: mdec-addr=0x55c2a0730710
09-30 15:47:43.080 534979 534979 E PLUGIN/CTF/META/DECODER ctf_metadata_decoder_append_content@decoder.c:258 [N/A] Invalid metadata version found in plain text signature: version=2691891360.21954, mdec-addr=0x55c2a0730710
09-30 15:47:43.080 534979 534979 W PLUGIN/SRC.CTF.FS/QUERY support_info_query@query.c:477 cannot append metadata content: metadata-decoder-status=-3
09-30 15:47:43.080 534979 534979 W LIB/QUERY-EXECUTOR bt_query_executor_query@query-executor.c:243 Component class's "query" method failed: query-exec-addr=0x55c2a072f790, cc-addr=0x55c2a07289d0, cc-type=SOURCE, cc-name="fs", cc-partial-descr="Read CTF traces from the file sy", cc-is-frozen=0, cc-so-handle-addr=0x55c2a0727e60, cc-so-handle-path="/home/kstewart/src/efficios/lttng/master/usr/lib/babeltrace2/plugins/babeltrace-plugin-ctf.so", object="babeltrace.support-info", params-addr=0x55c2a0728fe0, params-type=MAP, params-element-count=2, log-level=WARNING
09-30 15:47:43.080 534979 534979 E CLI-CFG-SRC-AUTO-DISC support_info_query_all_sources@autodisc.c:509 babeltrace.support-info query failed.
09-30 15:47:43.080 534979 534979 E CLI main@babeltrace2.c:2662 Command-line error: retcode=1

ERROR:    [Babeltrace CLI] (babeltrace2.c:2662)
  Command-line error: retcode=1
CAUSED BY [Source auto-discovery] (autodisc.c:509)
  babeltrace.support-info query failed.
CAUSED BY [libbabeltrace2] (query-executor.c:243)
  Component class's "query" method failed: query-exec-addr=0x55c2a072f790,
  cc-addr=0x55c2a07289d0, cc-type=SOURCE, cc-name="fs", cc-partial-descr="Read
  CTF traces from the file sy", cc-is-frozen=0,
  cc-so-handle-addr=0x55c2a0727e60,
  cc-so-handle-path="/home/kstewart/src/efficios/lttng/master/usr/lib/babeltrace2/plugins/babeltrace-plugin-ctf.so",
  object="babeltrace.support-info", params-addr=0x55c2a0728fe0, params-type=MAP,
  params-element-count=2, log-level=WARNING
```

Cause
=====

Since commit e9dbb91b6fa36cf5a8bdc222d6342e1cd4eee127 ("consumerd:
Always strip metadata packet header"), the binary metadata packet
header is removed from all metadata subbuffers as they are consumed.

In the case of the subbuffers created by lttng-modules, the
post-metadata packet header content does not contain the CTF
comment (e.g. `/* CTF 1.8 */`) as required for the text-only
metadata in the CTF specification[1].

Solution
========

For metadata streams in the kernel domain, write the CTF 1.x
announcement when the metadata is first pushed. Since the kernel
metadata consumption only ever uses the `mmap` path, only that
path is modified.

Known drawbacks
===============

This doesn't check the subbuffer content to validate if it already
contains a CTF announcement or not before writing one out.

This doesn't use the metadata packet header for sourcing the CTF
version for two reasons:

 * The CTF version set in the metadata packet header by the
 lttng-modules kernel tracer is 1.8, even if the output of
 the session is configure to use CTF 2, affects 2.14.0 to 2.14.2 at the
 time of this writing[2].

 * The natural place to source the CTF information is in
 `pre_consume`, before the metadata packet header is stripped from the
 subbuffer. When a metadata bucket is used, the final flushed data is
 attached to a freshly stack-allocated `struct stream_subbuffer` which
 is not passed via `pre_consume`, and the data that it contains already has
 the metadata packet header stripped.

References
==========

[1]: https://diamon.org/ctf/v1.8.3/#spec7.1
[2]: https://review.lttng.org/c/lttng-modules/+/15374

Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: I2e799766d76905f19f65cd6184d7e6f98a234d15