build: Add missing DEFINE_LTTNG_UST_SIGBUS_STATE();
Fixes:

  liblttng-ust-ctl.so: undefined reference to `lttng_ust_sigbus_state'

Signed-off-by: orbea <orbea@riseup.net>