Tests: retry trace validation after recording streaming snapshots
Observed issue
==============

Sporadic test failures in
`regression/tools/snapshots/test_ust_streaming` such as:

```
ok 8 - Added snapshot output net://localhost
PASS: tools/snapshots/test_ust_streaming 8 - Added snapshot output net://localhost
 # ./tools/snapshots//../../../../src/bin/lttng/lttng snapshot record -s FPbIQkWVRW1H0DBb
ok 9 - Snapshot recorded
PASS: tools/snapshots/test_ust_streaming 9 - Snapshot recorded
ok 10 - UST per-uid network snapshot trace path is valid
PASS: tools/snapshots/test_ust_streaming 10 - UST per-uid network snapshot trace path is valid
04-30 22:53:00.439 29149 29149 W PLUGIN/SRC.CTF.FS/DS build_index_from_stream_file@data-stream-file.c:888 [auto-disc-source-ctf-fs] Invalid packet size reported in file: stream="/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit/chan1_0", packet-offset=524288, packet-size-bytes=155648, file-size=655448
04-30 22:53:00.439 29149 29149 E PLUGIN/SRC.CTF.FS add_ds_file_to_ds_file_group@fs.c:806 [auto-disc-source-ctf-fs] Failed to index CTF stream file '/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit/chan1_0'
04-30 22:53:00.439 29149 29149 E PLUGIN/SRC.CTF.FS create_ds_file_groups@fs.c:977 [auto-disc-source-ctf-fs] Cannot add stream file `/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit/chan1_0` to stream file group
04-30 22:53:00.439 29149 29149 E PLUGIN/SRC.CTF.FS ctf_fs_component_create_ctf_fs_trace_one_path@fs.c:1206 [auto-disc-source-ctf-fs] Cannot create trace for `/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit`.
04-30 22:53:00.439 29149 29149 W LIB/GRAPH add_component_with_init_method_data@graph.c:977 Component initialization method failed: status=ERROR, comp-addr=0x1533890, comp-name="auto-disc-source-ctf-fs", comp-log-level=WARNING, comp-class-type=SOURCE, comp-class-name="fs", comp-class-partial-descr="Read CTF traces from the file sy", comp-class-is-frozen=1, comp-class-so-handle-addr=0x1542b40, comp-class-so-handle-path="/root/workspace/lttng-tools_master_root_slesbuild/babeltrace_version/stable-2.0/build/std/conf/agents/liburcu_version/master/node/sles15sp4-amd64-rootnode/platform/sles15sp4-amd64/deps/build/lib64/babeltrace2/plugins/babeltrace-plugin-ctf.so", comp-input-port-count=0, comp-output-port-count=0
04-30 22:53:00.439 29149 29149 E CLI cmd_run_ctx_create_components_from_config_components@babeltrace2.c:2301 Cannot create component: plugin-name="ctf", comp-cls-name="fs", comp-cls-type=1, comp-name="auto-disc-source-ctf-fs"
04-30 22:53:00.439 29149 29149 E CLI cmd_run@babeltrace2.c:2480 Cannot create components.

ERROR:    [Babeltrace CLI] (babeltrace2.c:2480)
  Cannot create components.
CAUSED BY [Babeltrace CLI] (babeltrace2.c:2301)
  Cannot create component: plugin-name="ctf", comp-cls-name="fs",
  comp-cls-type=1, comp-name="auto-disc-source-ctf-fs"
CAUSED BY [libbabeltrace2] (graph.c:977)
  Component initialization method failed: status=ERROR, comp-addr=0x1533890,
  comp-name="auto-disc-source-ctf-fs", comp-log-level=WARNING,
  comp-class-type=SOURCE, comp-class-name="fs", comp-class-partial-descr="Read
  CTF traces from the file sy", comp-class-is-frozen=1,
  comp-class-so-handle-addr=0x1542b40,
  comp-class-so-handle-path="/root/workspace/lttng-tools_master_root_slesbuild/babeltrace_version/stable-2.0/build/std/conf/agents/liburcu_version/master/node/sles15sp4-amd64-rootnode/platform/sles15sp4-amd64/deps/build/lib64/babeltrace2/plugins/babeltrace-plugin-ctf.so",
  comp-input-port-count=0, comp-output-port-count=0
CAUSED BY [auto-disc-source-ctf-fs: 'source.ctf.fs'] (fs.c:1206)
  Cannot create trace for
  `/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit`.
CAUSED BY [auto-disc-source-ctf-fs: 'source.ctf.fs'] (fs.c:977)
  Cannot add stream file
  `/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit/chan1_0`
  to stream file group
CAUSED BY [auto-disc-source-ctf-fs: 'source.ctf.fs'] (fs.c:806)
  Failed to index CTF stream file
  '/tmp/tmp.udperBSwkg/tmp.test_snapshots_ust_streaming_trace_path.qnQTJk/ci-rootnode-sles15sp4-amd64-1d-01/FPbIQkWVRW1H0DBb-20240430-225259/snapshot-1-20240430-225300-0/ust/uid/0/64-bit/chan1_0'
not ok 11 - Found 0 events matching 'tp:tptest'
FAIL: tools/snapshots/test_ust_streaming 11 - Found 0 events matching 'tp:tptest'
 #   Failed test 'Found 0 events matching 'tp:tptest''
 #   in :() at line 2144 validate_trace ./tools/snapshots//../../../utils/utils.sh.
 # ./tools/snapshots//../../../../src/bin/lttng/lttng snapshot
 # del-output -s FPbIQkWVRW1H0DBb 1
```

Cause
=====

When a remote snapshot location is remote, `lttng snapshot` returns
when the process of marshaling the snapshot on the session daemon is
done, which is not the same moment that the relay daemon has finished
writing all the data to disk.

This issue happens more often on SLE15SP5 than on other platforms.

Solution
========

Retry the trace validation with a small sleep to give some time for
the relayd to finish processing date. This is a work-around rather
than a solution.

An alternative and more robust solution is to have a notification post
snapshot record such that `snapshot record` waits to return until the
data is finished being written by the relayd. See this attempt[1].

Known drawbacks
===============

There are likely outlier cases where slow networks or slow disks could
further impact this.

The multiple sleeps increase the runtime of both tests.

References
==========

[1]: https://review.lttng.org/c/lttng-tools/+/6578/

Change-Id: Ief3220514f6600c36b4a09d4aba7613f0ba6099f
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>