tests: Do not expect `epoll_wait_*` on arm64 and riscv64
In the CI, rootbuilds on arm64 failed
`tests/regression/kernel/test_select_poll_epoll` as follows:

```
epoll_wait_in_ok not validated
Values of the local variables of this test:
Traceback (most recent call last):
  File "/root/master/src/lttng-tools/./tests/regression/kernel//validate_select_poll_epol
l.py", line 858, in <module>
    ret = t.parse()
          ^^^^^^^^^
  File "/root/master/src/lttng-tools/./tests/regression/kernel//validate_select_poll_epol
l.py", line 84, in parse
    pprint.pprint(self.recorded_values[event_name])
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'epoll_wait_entry'
not ok 12 - Validation
  ---
    duration_ms: 324.895520
  ...
```

This is due to `epoll_wait` not being a valid system call on those
architectures. When that system call is not defined, glibc will fall
back to using `epoll_pwait`[1].

[1]: https://github.com/bminor/glibc/commit/b62c3815912bc679a966134affdedd3f35ae8621

Change-Id: Id098ba32162649065671fd50f9a7e83bd3f57f16
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>