Remove unused function uri_create
Fixes:

      CC       uri.lo
    /home/smarchi/src/lttng-tools/src/common/uri.c:273:19: error: no previous declaration for ‘uri_create’ [-Werror=missing-declarations]
     struct lttng_uri *uri_create(void)
                       ^~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I18a58391842c3fba1fa3dd60cf5fe3215280f95a
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>