Build fix: sessiond: field: conflicting exception specification
The move constructor of variant_type_choice is declared noexcept.
However, older compilers such as gcc 4.8 generate default constructors
with a conflicting exception specification.

The resulting compilation error follows:

  field.hpp:518:2: error: function 'lttng::sessiond::trace::variant_type_choice<MappingIntegerType>::variant_type_choice(lttng::sessiond::trace::variant_type_choice<MappingIntegerType>&&) [with MappingIntegerType = long int]' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'lttng::sessiond::trace::variant_type_choice<long int>::variant_type_choice(lttng::sessiond::trace::variant_type_choice<long int>&&)'
    variant_type_choice(variant_type_choice&& other) noexcept = default;
    ^

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Change-Id: Ifc81a02da751bf56126cfb529fa29e6a452888b2