Build fix: Windows and macOS build failure due to MADV_REMOVE compat
The prototype of lttng::utils::fs_supports_madv_remove was
changed, but the compatibility wrapper used by these platforms
was not adapted, resulting in the following error:

fs-utils.cpp:166:6: error: declaration of 'bool lttng::utils::fs_supports_madv_remove(const char*)' has a different exception specifier
  166 | bool lttng::utils::fs_supports_madv_remove(const char *shm_path)
      |      ^~~~~
In file included from fs-utils.cpp:7:
fs-utils.hpp:13:6: note: from previous declaration 'bool lttng::utils::fs_supports_madv_remove(const char*) noexcept'
   13 | bool fs_supports_madv_remove(const char *shm_path = nullptr) noexcept;
      |      ^~~~~~~~~~~~~~~~~~~~~~~
fs-utils.cpp: In function 'bool lttng::utils::fs_supports_madv_remove(const char*)':
fs-utils.cpp:166:56: warning: unused parameter 'shm_path' [-Wunused-parameter]
  166 | bool lttng::utils::fs_supports_madv_remove(const char *shm_path)
      |                                            ~~~~~~~~~~~~^~~~~~~~

Change-Id: Iea2ff67eb2c9852bbc717e482271e7050ee88d1c
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>