sessiond: remove unused log_job_destruction function
Fixes:

      CC       rotation-thread.o
    /home/smarchi/src/lttng-tools/src/bin/lttng-sessiond/rotation-thread.c:114:6: error: no previous declaration for ‘log_job_destruction’ [-Werror=missing-declarations]
     void log_job_destruction(const struct rotation_thread_job *job)
          ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I3fce2aceb047a2a251d61e84bff5862be49fe593
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>