tests: Add missing lttng-ctl.suppr to extra dist
When running
`tests/regression/tools/lttng-ctl/test_liblttng-ctl_abi.py` from a
dist tarball, the build fails as follows:

    # Discovered liblttng-ctl version '0.0.0'
    # Generation command: `abidw --drop-undefined-syms --drop-private-types --headers-dir /home/jenkins/workspace/lttng-tools_master_linuxbuild/babeltrace_version/master/build/dist/conf/std/liburcu_version/master/platform/deb13-amd64/tmp/tmp.s0aKNu78Pi/include /home/jenkins/workspace/lttng-tools_master_linuxbuild/babeltrace_version/master/build/dist/conf/std/liburcu_version/master/platform/deb13-amd64/tmp/tmp.s0aKNu78Pi/src/lib/lttng-ctl/.libs/liblttng-ctl.so`
    # Diff command: `abidiff --suppressions /home/jenkins/workspace/lttng-tools_master_linuxbuild/babeltrace_version/master/build/dist/conf/std/liburcu_version/master/platform/deb13-amd64/tmp/tmp.s0aKNu78Pi/src/lib/lttng-ctl/abi_ref/lttng-ctl.suppr /home/jenkins/workspace/lttng-tools_master_linuxbuild/babeltrace_version/master/build/dist/conf/std/liburcu_version/master/platform/deb13-amd64/tmp/tmp.s0aKNu78Pi/src/lib/lttng-ctl/abi_ref/0.0.0/x86_64-64bit-linux/abi.xml /tmp/tmp.c3G940IAnM/tmpih1jpkxa`
    # ABI diff output:
    # abidiff: file /home/jenkins/workspace/lttng-tools_master_linuxbuild/babeltrace_version/master/build/dist/conf/std/liburcu_version/master/platform/deb13-amd64/tmp/tmp.s0aKNu78Pi/src/lib/lttng-ctl/abi_ref/lttng-ctl.suppr does not exist
    #
    1..1
    not ok 1 - Error running abidiff, return code '3'
    FAIL: tools/lttng-ctl/test_liblttng-ctl_abi.py 1 - Error running abidiff, return code '3'
    ERROR: tools/lttng-ctl/test_liblttng-ctl_abi.py - exited with status 1

Change-Id: I0c374bc080917f7c1c8bd0cfe935549dc1154792
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>