build: fix: OOT build fail when scripts include directories
Observed issue
==============

Some tests failed and caused the CI to hang, e.g.

```
$ ./tests/regression/tools/notification/test_notification_ust_error
./tests/regression/tools/notification//../../..//utils/utils.sh: line 77: ./tests/regression/tools/notification//../../..//utils/tap/tap.sh: No such file or directory
./tests/regression/tools/notification/test_notification_ust_error: line 42: tap_disable: command not found
./tests/regression/tools/notification//../../..//utils/utils.sh: line 1366: diag: command not found
./tests/regression/tools/notification//../../..//utils/utils.sh: line 1382: diag: command not found
Traceback (most recent call last):
  File "/tmp/tmp.Q6GWOsOba3/build/./tests/regression/tools/notification//util_event_generator.py", line 18, in <module>
    import lttngtest
ModuleNotFoundError: No module named 'lttngtest'
```

Cause
=====

The handling of EXTRA_DIST to copy files from the source to builddir
does not properly handle scripts that include directories.

Solution
========

Check to verify if the dirname of the script file is not ".", and
create the directories as needed before copying the script.

Known drawbacks
===============

None.

Change-Id: I67ff5cc09b93b57f668d816729fec641746b954a
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>