config: Propagate load error when loading from directory
Observed issue
==============

When loading an invalid session, the lttng load command would not
return a non-zero return code.

```
$ lttng load --input-path /path/to/directory saved_session
  XML Error: Element 'fake': This element is not expected.
  Error: Session configuration file validation failed
$ echo $?
0
```

If the file was given specifically, it would fail as expected:

```
$ lttng load --input-path /path/to/directory/saved_session.lttng
   XML Error: Element 'fake': This element is not expected.
   Error: Session configuration file validation failed
$ echo $?
1
```

Example invalid session:

```
<?xml version="1.0" encoding="UTF-8"?>
<sessions>
        <session>
                <name>asdf</name>
                <domains>
                        <domain>
                                <type>UST</type>
                                <buffer_type>PER_UID</buffer_type>
                                <channels>
                                        <channel>
                                                <name>channel0</name>
                                                <enabled>true</enabled>
                                                <overwrite_mode>DISCARD</overwrite_mode>
                                                <subbuffer_size>524288</subbuffer_size>
                                                <subbuffer_count>4</subbuffer_count>
                                                <switch_timer_interval>0</switch_timer_interval>
                                                <read_timer_interval>0</read_timer_interval>
                                                <output_type>MMAP</output_type>
                                                <blocking_timeout>0</blocking_timeout>
                                                <allocation_policy>PER_CPU</allocation_policy>
                                                <monitor_timer_interval>1000000</monitor_timer_interval>
                                                <watchdog_timer_interval>2000000</watchdog_timer_interval>
                                                <tracefile_size>0</tracefile_size>
                                                <tracefile_count>0</tracefile_count>
                                                <live_timer_interval>0</live_timer_interval>
                                                <fake>0</fake>
                                                <events>
                                                        <event>
                                                                <name>*</name>
                                                                <enabled>true</enabled>
                                                                <type>TRACEPOINT</type>
                                                                <loglevel_type>ALL</loglevel_type>
                                                        </event>
                                                </events>
                                                <contexts>
                                                        <context>
                                                                <type>CPU_ID</type>
                                                        </context>
                                                </contexts>
                                        </channel>
                                </channels>
                                <process_attr_trackers/>
                        </domain>
                        <domain>
                                <type>JUL</type>
                                <buffer_type>PER_UID</buffer_type>
                                <channels/>
                        </domain>
                        <domain>
                                <type>LOG4J</type>
                                <buffer_type>PER_UID</buffer_type>
                                <channels/>
                        </domain>
                        <domain>
                                <type>LOG4J2</type>
                                <buffer_type>PER_UID</buffer_type>
                                <channels/>
                        </domain>
                        <domain>
                                <type>PYTHON</type>
                                <buffer_type>PER_UID</buffer_type>
                                <channels/>
                        </domain>
                </domains>
                <started>false</started>
                <output>
                        <consumer_output>
                                <enabled>true</enabled>
                                <destination>
                                        <path>/home/kstewart/src/efficios/lttng/master/home/lttng-traces/asdf-20251006-114258</path>
                                </destination>
                        </consumer_output>
                </output>
        </session>
</sessions>
```

Cause
=====

`load_session_from_path` masks the error code

Solution
========

Don't force the return code to be a success.

Known drawbacks
===============

None.

Change-Id: Ib8046d006cdfdff102371f539223159f3988e336
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>