Make fd_count function static in test_fd_tracker.c
Fixes:

      CC test_fd_tracker.o
    /home/smarchi/src/lttng-tools/tests/unit/test_fd_tracker.c:65:5:
    error: no previous declaration for ‘fd_count’
    [-Werror=missing-declarations] int fd_count(void) ^~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I02775d5d601211052b4cad323bc33623beabc8f9
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>