config: accept "0" and "1" as XML boolean values
These are valid values when validating a "boolean" using a schema (XSD).
Somebody could therefore write a file with

    <started>0</started>

instead of

    <started>false</started>

The file would validate against session.xsd, but we would fail after
that:

    Warning: Invalid boolean value encoutered (0).
    Error: Invalid session configuration

Reference: https://www.w3.org/TR/xmlschema11-2/#boolean

Change-Id: Icea85b13233ec01aa09ef3b578906f4c0e482088
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>