Fix: support Python 3.5 in `tools/lttng-ctl/test_robust_protocol.py`
On yocto23 powerpc32 the following failure was observed:

    ERROR: tools/lttng-ctl/test_robust_protocol.py
    ==============================================

    Traceback (most recent call last):
      File "./tools/lttng-ctl/test_robust_protocol.py", line 126, in <module>
        if not os.path.exists(path_to_fuzz_lib):
      File "/usr/lib/python3.5/genericpath.py", line 19, in exists
        os.stat(path)
    TypeError: argument should be string, bytes or integer, not PosixPath
    1..1
    Bail out! Missing 1 test cases
    ERROR: tools/lttng-ctl/test_robust_protocol.py - Bail out! Missing 1 test cases
    Exception ignored in: <bound method TapGenerator.__del__ of <lttngtest.tap_generator.TapGenerator object at 0xb7bce490>>
    Traceback (most recent call last):
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 112, in __del__
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/src/lttng-tools/tests/utils/lttngtest/tap_generator.py", line 160, in bail_out
    lttngtest.tap_generator.BailOut: Missing 1 test cases

`os.path.exists` in Python 3.5 does not support pathlib.Path

Change-Id: Iaf5db7df5e7d29df318f53fca63d3969015285f3
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>