tests: add declaration for test_function in userspace-probe-elf-binary.c
Fixes:

      CC       userspace-probe-elf-binary.o
    /home/smarchi/src/lttng-tools/tests/utils/testapp/userspace-probe-elf-binary/userspace-probe-elf-binary.c:21:34: error: no previous declaration for ‘test_function’ [-Werror=missing-declarations]
     void __attribute__ ((noinline))  test_function()
                                      ^~~~~~~~~~~~~

I did not make test_function static, because from what I understand, it
is important that test_function remains an exported symbol, for example
for test regression/kernel/test_userspace_probe.

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I52019f69de023b24b46cc701e2e0df919e654a76
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>