consumerd: make lttng_consumer_close_all_metadata static
It is only used in its file, so make it static.  Fixes:

      CC       consumer.lo
    /home/smarchi/src/lttng-tools/src/common/consumer/consumer.c:2177:6: error: no previous declaration for ‘lttng_consumer_close_all_metadata’ [-Werror=missing-declarations]
     void lttng_consumer_close_all_metadata(void)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I211a31a7fb5edfb76e90f1209e69bbed5dd5ec92
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>