tests: Handle fragments being returned as bytes
On yocto23-powerpc with Python 3.5, failures were seen such as
follows in ust/clock-override-test_clock_override_ust and others:

    Traceback (most recent call last):
      File "ust/clock-override//../../../utils/extract_ctf_2_prop.py", line 72, in <module>
        _main()
      File "ust/clock-override//../../../utils/extract_ctf_2_prop.py", line 62, in _main
        values = extract_prop(sys.argv[1], sys.argv[2], sys.argv[3])
      File "ust/clock-override//../../../utils/extract_ctf_2_prop.py", line 27, in extract_prop
        obj = json.loads(fragment)
      File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'
    not ok 11 - Token "name" expect:lttng_test_clock_override got:

Change-Id: Idc8b45d0794f21ef2fa72f831ec62ec5662845ca
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>