tests: Fix platform uname split when release contains more periods
OBSERVED ISSUE
━━━━━━━━━━━━━━

When running `test_regenerate_rotate.py` on el8, the test fails as
follows:

    Traceback (most recent call last):
      File "tools/regen-metadata/test_regenerate_rotate.py", line 265, in setup
        major, minor, _ = platform.uname().release.split(".", 3)
    ValueError: too many values to unpack (expected 3)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "tools/regen-metadata/test_regenerate_rotate.py", line 332, in <module>
        raise e
      File "tools/regen-metadata/test_regenerate_rotate.py", line 329, in <module>
        output_path, teardown_commands = setup(tap)
      File "tools/regen-metadata/test_regenerate_rotate.py", line 308, in setup
        teardown_commands, "Exception during setup: {}".format(str(e))

CAUSE
━━━━━

`platform.uname().release` returns `4.18.0-553.27.1.el8_10.x86_64`,
which gets turned into a 4-tuple when `maxsplit` is 3.

From the python documentation[1]:

    If maxsplit is given, at most maxsplit splits are done (thus, the
    list will have at most maxsplit+1 elements). If maxsplit is not
    specified or -1, then there is no limit on the number of splits
    (all possible splits are made).

SOLUTION
━━━━━━━━

Only split up to twice.

KNOWN DRAWBACKS
━━━━━━━━━━━━━━━

Arguably this is still fairly brittle, and would fail if
`uname().release` is something like `4.18` instead of `4.18.0`

REFERENCES
━━━━━━━━━━

[1]: https://docs.python.org/3.6/library/stdtypes.html#str.split

Change-Id: Idb840ebf58291a4d56813de72c42802d390467cd
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>