Include cmd-2-2.h in cmd-2-1.h
Fixes:

      CC cmd-2-2.o
    /home/smarchi/src/lttng-tools/src/bin/lttng-relayd/cmd-2-2.c:36:5:
    error: no previous declaration for ‘cmd_recv_stream_2_2’
    [-Werror=missing-declarations] int cmd_recv_stream_2_2(const
    struct lttng_buffer_view *payload, ^~~~~~~~~~~~~~~~~~~

... and helps ensure that the declarations are in sync with the
definitions.

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I889d7306c157b0d68d24bf610fce18c8949422d8
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>