Fix time going backward for inactive live streams
Observed Issue
==============

Using the stream creation time to lazily stamp the first packet within a
stream is problematic for live sessions. An inactive stream will have
inactivity beacons claiming no activity up to a given timestamp, but can
then emit the timestamp_begin with the creation timestamp, which is
prior to the last inactivity beacon timestamp. This is inconsistent
from the perspective of the lttng live protocol.

This causes tools/live/test_lttng_ust_two_apps.py (run as root with
destructive tests for per-uid buffers) to fail with:

Traceback (most recent call last):
  File "/home/compudj/git/lttng-tools/tests/regression/tools/live/./test_lttng_ust_two_apps.py", line 124, in <module>
    test_lttng_ust_two_apps(tap, test_env, buffer_sharing_policy)
  File "/home/compudj/git/lttng-tools/tests/regression/tools/live/./test_lttng_ust_two_apps.py", line 95, in test_lttng_ust_two_apps
    viewer.wait(close_iterator=False)
  File "/home/compudj/git/lttng-tools/tests/utils/lttngtest/environment.py", line 237, in wait
    self._drain(retry=True, timeout=timeout)
  File "/home/compudj/git/lttng-tools/tests/utils/lttngtest/environment.py", line 167, in _drain
    for msg in self._live_iterator:
  File "/usr/local/lib/python3.11/dist-packages/bt2/trace_collection_message_iterator.py", line 414, in __next__
    self._graph.run_once()
  File "/usr/local/lib/python3.11/dist-packages/bt2/graph.py", line 207, in run_once
    bt2_utils._handle_func_status(
  File "/usr/local/lib/python3.11/dist-packages/bt2/utils.py", line 166, in _handle_func_status
    raise bt2_error._Error(msg)
bt2.error._Error: graph object could not run once
ERROR:    [libbabeltrace2] (lib/graph/graph.c:464)
  Component's "consume" method failed: status=ERROR, comp-addr=0x1a516810,
  comp-name="proxy-sink", comp-log-level=NONE, comp-class-type=SINK,
  comp-class-name="_TraceCollectionMessageIteratorProxySink",
  comp-class-partial-descr="", comp-class-is-frozen=0, comp-input-port-count=1,
  comp-output-port-count=0
CAUSED BY [proxy-sink: 'sink._TraceCollectionMessageIteratorProxySink'] (bt2/native_bt_log_and_append_error.hpp:101)
  Traceback (most recent call last):
    File
  "/usr/local/lib/python3.11/dist-packages/bt2/trace_collection_message_iterator.py",
  line 287, in _user_consume
      self._msg_list[0] = next(self._msg_iter)
                          ^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/bt2/message_iterator.py", line
  50, in __next__
      bt2_utils._handle_func_status(
    File "/usr/local/lib/python3.11/dist-packages/bt2/utils.py", line 166, in
  _handle_func_status
      raise bt2_error._Error(msg)
  bt2._Error: unexpected error: cannot advance the message iterator
CAUSED BY [libbabeltrace2] (lib/graph/iterator.c:1341)
  Component input port message iterator's "next" method failed:
  iter-addr=0x1a62c780, iter-upstream-comp-name="muxer",
  iter-upstream-comp-log-level=NONE, iter-upstream-comp-class-type=FILTER,
  iter-upstream-comp-class-name="muxer",
  iter-upstream-comp-class-partial-descr="Sort messages from multiple inpu",
  iter-upstream-port-type=OUTPUT, iter-upstream-port-name="out", status=ERROR
CAUSED BY [libbabeltrace2] (lib/graph/iterator.c:1341)
  Component input port message iterator's "next" method failed:
  iter-addr=0x1a608800, iter-upstream-comp-name="lttng-live",
  iter-upstream-comp-log-level=NONE, iter-upstream-comp-class-type=SOURCE,
  iter-upstream-comp-class-name="lttng-live",
  iter-upstream-comp-class-partial-descr="Connect to an LTTng relay daemon",
  iter-upstream-port-type=OUTPUT, iter-upstream-port-name="out", status=ERROR
CAUSED BY [lttng-live: 'source.ctf.lttng-live'] (plugins/ctf/lttng-live/lttng-live.cpp:1452)
  Error preparing the next batch of messages:
  live-iter-status=LTTNG_LIVE_ITERATOR_STATUS_ERROR
CAUSED BY [lttng-live: 'source.ctf.lttng-live'] (plugins/ctf/lttng-live/lttng-live.cpp:1033)
  Late message could not be handled correctly:
  lttng-live-msg-iter-addr=0x1a3a38e0, stream-name="stream-1",
  curr-msg-ts=1764705330664761065, last-msg-ts=1764705331730540014
CAUSED BY [lttng-live: 'source.ctf.lttng-live'] (plugins/ctf/lttng-live/lttng-live.cpp:893)
  Invalid live stream state: have a late message that is not a packet discarded
  or event discarded message: late-msg-type=PacketBeginning
1..4
Bail out! Missing 4 test case

Solution
========

Use a newly introduced lttng_ust_ctl_timestamp_sync() ust-ctl API, which
allows the live beacon to ensure no timestamps can be emitted in the
past for this stream after this synchronization function returns.

This depends on the LTTng-UST commit "Introduce lttng_ust_ctl_timestamp_sync".

Known drawbacks
===============

Similarly to "lttng stop", the first live beacon timer will require
allocation of one backing page per CPU in the system for each inactive
stream. This burst of memory use is temporary if the memory is reclaimed
by the consumer daemon afterward.

Depends-on: lttng-ust: Ide3b82c88ac527946400c9e1e89662700d837a00
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Change-Id: I2a841dcc9b0a85aa7f8ac98eadeb30a595cbd8b0
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>