tests: Fix string formatting for Python 3.4+
Observed Issue
==============

When running
`./tests/regression/ust/high-throughput/test_high_throughput_snapshot.py`
on yocto23 or sles12sp5, the test fails with the following error:

```
$ ./tests/regression/ust/high-throughput/test_high_throughput_snapshot.py
  File "./tests/regression/ust/high-throughput/test_high_throughput_snapshot.py", line 38
    return " ".join(f"{byte:02x}" for byte in b)
                                ^
SyntaxError: invalid syntax
```

Cause
=====

f-strings are only available in python 3.6+.

Solution
========

Use `str.format()` instead

Known drawbacks
===============

None.

Change-Id: Ieb055628c491255305afd31f6951b2cbf8d3050e
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>