Build fix: build without lttng-ust
Add conditionnal inclusion of ust-sigbus to the tests modified by:

  commit e207fe73b58787c6077ec5d49254e12ff1a82b51
  Author: orbea <orbea@riseup.net>
  Date:   Sat May 29 11:07:41 2021 -0700

    build: Add missing DEFINE_LTTNG_UST_SIGBUS_STATE();

    Fixes:

      liblttng-ust-ctl.so: undefined reference to `lttng_ust_sigbus_state'

Change-Id: If4af7ada6d94ee67603156d151575dcc57baad05
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>