tests: Fix `compound with` statements require Python 3.9+
Fails on older axes such as el8:

    Traceback (most recent call last):
      File "tools/map/test_kernel_map_channel_integration.py", line 46, in <module>
        import common
      File "/home/jenkins/workspace/lttng-tools_master_elbuild/babeltrace_version/stable-2.1/build/std/conf/agents/liburcu_version/master/platform/el8-amd64/src/lttng-tools/tests/regression/tools/map/common.py", line 451
        ) as test_env,
           ^
    SyntaxError: invalid syntax

Note: the 3.9 comes from what `vermin -t=3.6- --violations`
reports. From the online docs I think it might actually be 3.10.

Refs: https://docs.python.org/3/reference/compound_stmts.html#the-with-statement
Change-Id: I8649999ef77243951483e7584e79ef9c71da5d22
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>